spring:
  application:
    name: rutas-ods-backend
  datasource:
    url: jdbc:h2:mem:rutasods
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false

server:
  port: 8081

osrm:
  base-url: "https://router.project-osrm.org"
  profile: "driving"
  chunk-size: 40
  timeout-seconds: 20
